-- AlterTable
ALTER TABLE "Project" ALTER COLUMN "title" DROP DEFAULT,
ALTER COLUMN "description" DROP DEFAULT,
ALTER COLUMN "fileUrl" DROP DEFAULT,
ALTER COLUMN "demoUrl" DROP DEFAULT,
ALTER COLUMN "metaDescription" DROP DEFAULT,
ALTER COLUMN "metaKeywords" DROP DEFAULT,
ALTER COLUMN "metaTitle" DROP DEFAULT,
ALTER COLUMN "repositoryUrl" DROP DEFAULT,
ALTER COLUMN "robots" SET DEFAULT 'index,follow',
ALTER COLUMN "projectImage" DROP DEFAULT,
ALTER COLUMN "features" DROP DEFAULT,
ALTER COLUMN "requirements" DROP DEFAULT,
ALTER COLUMN "videoUrl" DROP DEFAULT;
